[".local/share/zsh/zsh-autosuggestions.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/zsh-users/zsh-autosuggestions/master/zsh-autosuggestions.zsh"

[".local/share/zsh/zsh-tab-title.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/trystan2k/zsh-tab-title/master/zsh-tab-title.plugin.zsh"

[".asdf"]
    type = "git-repo"
    url = "https://github.com/asdf-vm/asdf.git"
