[".local/share/zsh/zsh-autosuggestions.zsh"]
    url = "https://raw.githubusercontent.com/zsh-users/zsh-autosuggestions/master/zsh-autosuggestions.zsh"
    type = "file"

[".local/share/zsh/zsh-tab-title.zsh"]
    url = "https://raw.githubusercontent.com/trystan2k/zsh-tab-title/master/zsh-tab-title.plugin.zsh"
    type = "file"

[".asdf"]
    url = "https://github.com/asdf-vm/asdf.git"
    type = "git-repo"

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
    url = "https://github.com/wbthomason/packer.nvim.git"
    type = "git-repo"

{{ if eq .chezmoi.os "darwin" -}}
[".hammerspoon/Spoons/"]
    url     = "https://github.com/Hammerspoon/Spoons/raw/master/Spoons/SpoonInstall.spoon.zip"
    type    = "archive"
    exclude = ["docs.json"]
{{ end -}}

