["bin/rtx"]
  {{ if eq .chezmoi.os "darwin" -}}
    url = "https://rtx.pub/rtx-latest-macos-arm64"
  {{ else -}}
    url = "https://rtx.pub/rtx-latest-linux-amd64"
  {{ end -}}
    type = "file"
    executable = true
    refreshPeriod = "168h"

[".local/share/nvim/lazy/lazy.nvim"]
    url = "https://github.com/folke/lazy.nvim.git"
    type = "git-repo"
    [".local/share/nvim/lazy/lazy.nvim" .clone]
      args = ["--branch=stable", "--filter=blob:none"]
