brew "atuin"
brew "gitui"
brew "stylua"
brew "blueutil"
brew "trash"
brew "chezmoi"
brew "lua"
brew "mysql-client"
brew "python@3.9"
brew "tree-sitter"
brew "htop"
brew "luajit"
brew "rbenv"
brew "ncurses"
brew "fd"
brew "neovim"
brew "redis"
brew "fzf"
brew "ripgrep"
brew "elasticsearch-full"
brew "syncthing", enable_service: true
brew "mysql@5.7", restart_service: true, link: true, conflicts_with: ["mysql"]
cask "qutebrowser"
cask "sequel-ace"
cask "keepassxc", greedy: true
cask "hammerspoon", greedy: true
