#!/usr/bin/env bash
#
[ -x "/opt/homebrew/bin/brew" ] && eval "$(/opt/homebrew/bin/brew shellenv)"
[ -x "$(command -v starship)" ] &&  eval "$(starship init bash)"

PS1=' $ '
alias ls='ls -F --color=auto --hyperlink=auto'
alias ll='ls -lah'
alias rm=trash

export DATADIR=~/.local/share/mysql
export INPUT_METHOD=fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
export NOTES_DIR=~/Sync/20-29-Personal/20-Notes
export NNN_TMPFILE=~/.config/nnn/.lastd
export XDG_DATA_HOME=~/.local/share
export PAGER='less -SFX'
export EDITOR=nvim
export VISUAL=$EDITOR
export TERM=xterm-256color
export HISTFILE=~/.cache/history
export HISTSIZE=10000
export SAVEHIST=10000
export NO_COLOR=1
export FZF_DEFAULT_OPTS="--reverse --preview-window up,1,border-horizontal,hidden --bind 'ctrl-/:change-preview-window(50%|hidden)'"

PATH="$PATH":~/.local/bin
PATH="$PATH":~/bin
PATH="$PATH":"$GOPATH"/bin
PATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"
export PATH

[ -x "$(command -v rtx)" ] && eval "$(rtx activate bash)"

[ ! -f ~/.bashrc.local ] || . "$HOME"/.bashrc.local
[ ! -f .env ] || {
  set -o allexport
  source .env
  set +o allexport
}
