vim.cmd.hi("clear")

if vim.fn.exists("syntax_on") then
  vim.cmd.syntax("reset")
end

vim.g.colors_name = "typograph"
vim.o.termguicolors = true

local colors = {
  ['Normal'] = { ctermfg = 'NONE', ctermbg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['NonText'] = { bg = 'NONE', fg = '#808080' },
  ['Comment'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = '#808080', italic = true },
  ['Constant'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['Error'] = { ctermbg = 15, ctermfg = 9, bg = '#ffffff', fg = '#ff0000', reverse = true },
  ['Identifier'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', bold = true },
  ['Ignore'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['PreProc'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['Special'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', italic = true },
  ['Statement'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', bold = true },
  ['Todo'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', reverse = true },
  ['Type'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', bold = true, italic = true },
  ['Underlined'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', underline = true },
  ['StatusLine'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', },
  ['StatusLineNC'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', underline = true },
  ['StatusLineTerm'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', reverse = true },
  ['StatusLineTermNC'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', underline = true },
  ['VertSplit'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['TabLine'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['TabLineFill'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['TabLineSel'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', reverse = true },
  ['Title'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['CursorLine'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'black', fg = '#F1F7FF', reverse = true },
  ['LineNr'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = '#808080' },
  ['CursorLineNr'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', bold = true },
  ['helpLeadBlank'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['helpNormal'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['Visual'] = { ctermbg = 'NONE', ctermfg = 'darkcyan', bg = 'NONE', fg = 'darkcyan', reverse = true, bold = true },
  ['VisualNOS'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['Pmenu'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', },
  ['PmenuSbar'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = '#666666', fg = 'NONE', bold = true, reverse = true },
  ['PmenuSel'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'darkcyan', reverse = true, bold = true },
  ['PmenuThumb'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['FoldColumn'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['Folded'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['WildMenu'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['SpecialKey'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['DiffAdd'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['DiffChange'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['DiffDelete'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['DiffText'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['IncSearch'] = { ctermbg = 10, ctermfg = 0, bg = '#00ff00', fg = '#000000' },
  ['Search'] = { ctermbg = 11, ctermfg = 0, bg = '#fff2be', fg = '#000000' },
  ['Directory'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', bold = true },
  ['MatchParen'] = { ctermbg = 'NONE', ctermfg = 'green', bg = 'NONE', fg = 'green', reverse = true },
  ['SpellBad'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', sp = '#ff0000' },
  ['SpellCap'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', sp = '#0000ff' },
  ['SpellLocal'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', sp = '#ff00ff' },
  ['SpellRare'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE', sp = '#00ffff' },
  ['ColorColumn'] = { ctermbg = 'darkred', ctermfg = 'NONE', bg = 'darkred', fg = 'NONE' },
  ['SignColumn'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['ModeMsg'] = { ctermbg = 'NONE', ctermfg = 10, bg = 'NONE', fg = 'NONE' },
  ['MoreMsg'] = { ctermbg = 'NONE', ctermfg = 13, bg = 'NONE', fg = '#ff00ff' },
  ['Question'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['WarningMsg'] = { ctermbg = 'NONE', ctermfg = 9, bg = 'NONE', fg = '#ff0000' },
  ['Cursor'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['CursorColumn'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['QuickFixLine'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['Conceal'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['ToolbarLine'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['ToolbarButton'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['debugPC'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['debugBreakpoint'] = { ctermbg = 'NONE', ctermfg = 'NONE', bg = 'NONE', fg = 'NONE' },
  ['WinSeparator'] = { bg = 'NONE' },
  -- ['@lsp.type.namespace'] = '@type',
  -- ['@lsp.type.type'] = '@type',
  -- ['@lsp.type.class'] = '@type',
  -- ['@lsp.type.enum'] = '@type',
  -- ['@lsp.type.interface'] = '@type',
  -- ['@lsp.type.struct'] = '@structure',
  -- ['@lsp.type.parameter'] = { bg = "NONE", fg = "NONE" },
  ['@lsp.type.variable'] = { bg = 'NONE', fg = 'NONE', italic = true },
  -- ['@lsp.type.property'] = '@property',
  -- ['@lsp.type.enumMember'] = '@constant',
  -- ['@lsp.type.function'] = '@function',
  -- ['@lsp.type.method'] = '@method',
  -- ['@lsp.type.macro'] = '@macro',
  ['@lsp.type.decorator'] = { bg = 'NONE', fg = 'NONE', italic = true },
  ['CopilotSuggestion'] = { fg = '#555555', ctermfg = 8 },
}

for group, opts in pairs(colors) do
  vim.api.nvim_set_hl(0, group, opts)
end
