require('utils')
cmd [[autocmd TermOpen * setlocal nonumber norelativenumber]]
cmd [[tnoremap <Esc> <C-\><C-n>]]
cmd [[tnoremap <A-h> <C-\><C-N><C-w>h]]
cmd [[tnoremap <A-j> <C-\><C-N><C-w>j]]
cmd [[tnoremap <A-k> <C-\><C-N><C-w>k]]
cmd [[tnoremap <A-l> <C-\><C-N><C-w>l]]
cmd [[inoremap <A-h> <C-\><C-N><C-w>h]]
cmd [[inoremap <A-j> <C-\><C-N><C-w>j]]
cmd [[inoremap <A-k> <C-\><C-N><C-w>k]]
cmd [[inoremap <A-l> <C-\><C-N><C-w>l]]
cmd [[nnoremap <A-h> <C-w>h]]
cmd [[nnoremap <A-j> <C-w>j]]
cmd [[nnoremap <A-k> <C-w>k]]
cmd [[nnoremap <A-l> <C-w>l]]
