vim.cmd [[autocmd TermOpen * setlocal nonumber norelativenumber]]
vim.cmd [[tnoremap <Esc> <C-\><C-n>]]
vim.cmd [[tnoremap <A-h> <C-\><C-N><C-w>h]]
vim.cmd [[tnoremap <A-j> <C-\><C-N><C-w>j]]
vim.cmd [[tnoremap <A-k> <C-\><C-N><C-w>k]]
vim.cmd [[tnoremap <A-l> <C-\><C-N><C-w>l]]
vim.cmd [[inoremap <A-h> <C-\><C-N><C-w>h]]
vim.cmd [[inoremap <A-j> <C-\><C-N><C-w>j]]
vim.cmd [[inoremap <A-k> <C-\><C-N><C-w>k]]
vim.cmd [[inoremap <A-l> <C-\><C-N><C-w>l]]
vim.cmd [[nnoremap <A-h> <C-w>h]]
vim.cmd [[nnoremap <A-j> <C-w>j]]
vim.cmd [[nnoremap <A-k> <C-w>k]]
vim.cmd [[nnoremap <A-l> <C-w>l]]
