return {
	"famiu/bufdelete.nvim",
	"jghauser/mkdir.nvim",
	"jose-elias-alvarez/null-ls.nvim",
	"windwp/nvim-autopairs",
	"lukas-reineke/indent-blankline.nvim",
	"tpope/vim-eunuch",
	"vim-test/vim-test",
	"lewis6991/impatient.nvim",
	"linty-org/readline.nvim",
	"numToStr/Comment.nvim",
	"lewis6991/gitsigns.nvim",
	"tpope/vim-dadbod",
	"kristijanhusak/vim-dadbod-ui",
  "junegunn/vim-easy-align",
  "ThePrimeagen/harpoon",
  "williamboman/mason.nvim",
  "williamboman/mason-lspconfig.nvim",
  "neovim/nvim-lspconfig",
	{ "github/copilot.vim", opt = true },

	"hrsh7th/cmp-buffer",
	"hrsh7th/cmp-nvim-lsp",
	"hrsh7th/cmp-path",
	"hrsh7th/nvim-cmp",
	"lukas-reineke/cmp-rg",
	"sindrets/diffview.nvim",
	"TimUntersberger/neogit",
	"tpope/vim-vinegar",

	"nvim-telescope/telescope.nvim",
	"nvim-telescope/telescope-smart-history.nvim",
	"nvim-lua/plenary.nvim",
	"nvim-lua/popup.nvim",
	"neovim/nvim-lspconfig",
	"nvim-treesitter/nvim-treesitter",
}
