return {
	"akinsho/toggleterm.nvim",
	"famiu/bufdelete.nvim",
	"folke/zen-mode.nvim",
	"jghauser/mkdir.nvim",
	"jose-elias-alvarez/null-ls.nvim",
	"windwp/nvim-autopairs",
	"lukas-reineke/indent-blankline.nvim",
	"tpope/vim-eunuch",
	"vim-test/vim-test",
	"kchmck/vim-coffee-script",
	"lewis6991/impatient.nvim",
	"linty-org/readline.nvim",
	"norcalli/nvim-colorizer.lua",
	"numToStr/Comment.nvim",
	"lewis6991/gitsigns.nvim",
	"tpope/vim-dadbod",
	"kristijanhusak/vim-dadbod-ui",
	{ "github/copilot.vim", opt = true },

	"hrsh7th/cmp-buffer",
	"hrsh7th/cmp-nvim-lsp",
	"hrsh7th/cmp-path",
	"hrsh7th/nvim-cmp",
	"lukas-reineke/cmp-rg",

	"justinmk/vim-dirvish",
	"roginfarrer/vim-dirvish-dovish",

	"nvim-telescope/telescope.nvim",
	{ "nvim-telescope/telescope-fzf-native.nvim", run = "make" },

	"nvim-lua/plenary.nvim",
	"nvim-lua/popup.nvim",
	"neovim/nvim-lspconfig",
	"nvim-treesitter/nvim-treesitter",
}
